name: Tests & Coverage

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ladderly-io

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: './ladderly-io/package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Check test coverage
        run: |
          # Run tests and capture output
          OUTPUT=$(npm run test:cov)
          echo "$OUTPUT"

          # Extract branch coverage using grep and awk
          BRANCH_COVERAGE=$(echo "$OUTPUT" | grep "All files" | awk '{print $4}')

          if [ -z "$BRANCH_COVERAGE" ]; then
            echo "Error: Could not find branch coverage in test output!"
            exit 1
          fi

          if (( $(echo "$BRANCH_COVERAGE < 50" | bc -l) )); then
            echo "Branch coverage ($BRANCH_COVERAGE%) is below minimum threshold (30%)"
            exit 1
          fi
          echo "Branch coverage: $BRANCH_COVERAGE%"
