name: Tests & Coverage

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ladderly-io

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: './ladderly-io/package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Run tests with coverage
        run: npm run test:cov

      - name: Check coverage thresholds
        run: |
          BRANCH_COVERAGE=$(cat coverage/coverage-summary.json | jq -r '.total.branches.pct')
          if (( $(echo "$BRANCH_COVERAGE < 30" | bc -l) )); then
            echo "Branch coverage ($BRANCH_COVERAGE%) is below minimum threshold (30%)"
            exit 1
          fi
          echo "Branch coverage: $BRANCH_COVERAGE%"

      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: ladderly-io/coverage/
